import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, RefreshCw, Rocket, Save } from "lucide-react";
import * as React from "react";
import { Link, useParams } from "react-router";
import { api } from "@/api/client";
import type { Diagnostic } from "@/api/types";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { parseSpec, serializeSpec, SpecEditor, type SpecFormat } from "@/components/strategy/spec-editor";

export function StrategyDetailPage() {
  const { tenantId = "", projectId = "", strategyId = "" } = useParams(); const client = useQueryClient();
  const strategies = useQuery({ queryKey: ["strategies", tenantId, projectId], queryFn: () => api.listStrategies(tenantId, projectId) });
  const strategy = strategies.data?.items.find((item) => item.strategyId === strategyId);
  const draft = useQuery({ queryKey: ["draft", tenantId, projectId, strategyId, strategy?.draftId], queryFn: () => api.getDraft(tenantId, projectId, strategyId, strategy?.draftId ?? ""), enabled: Boolean(strategy?.draftId) });
  const versions = useQuery({ queryKey: ["versions", tenantId, projectId, strategyId], queryFn: () => api.listVersions(tenantId, projectId, strategyId) });
  const [format, setFormat] = React.useState<SpecFormat>("json"); const [source, setSource] = React.useState(""); const [diagnostics, setDiagnostics] = React.useState<Diagnostic[]>([]); const [message, setMessage] = React.useState("");
  React.useEffect(() => { if (draft.data && !source) setSource(serializeSpec(draft.data.spec, format)); }, [draft.data, format, source]);
  const parsed = () => parseSpec(source, format);
  const save = useMutation({ mutationFn: () => api.updateDraft(tenantId, projectId, strategyId, draft.data?.draftId ?? "", draft.data?.revision ?? 0, parsed()), onSuccess: async () => { setMessage("Draft saved."); await Promise.all([client.invalidateQueries({ queryKey: ["draft", tenantId, projectId, strategyId] }), client.invalidateQueries({ queryKey: ["strategies", tenantId, projectId] })]); }, onError: (error) => setMessage(error.message) });
  const compile = useMutation({ mutationFn: () => api.compileStrategy(tenantId, projectId, parsed()), onSuccess: (result) => { const hash = result.plan?.["plan_hash"]; setDiagnostics(result.diagnostics); setMessage(result.valid ? `Valid plan · ${typeof hash === "string" ? hash : ""}` : "Compilation found errors."); }, onError: (error) => setMessage(error.message) });
  const publish = useMutation({ mutationFn: async () => { await api.updateDraft(tenantId, projectId, strategyId, draft.data?.draftId ?? "", draft.data?.revision ?? 0, parsed()); return api.publishStrategy(tenantId, projectId, strategyId, draft.data?.draftId ?? ""); }, onSuccess: async (result) => { setMessage(`Published version ${result.version} · ${result.planHash}`); await Promise.all([client.invalidateQueries({ queryKey: ["draft", tenantId, projectId, strategyId] }), client.invalidateQueries({ queryKey: ["versions", tenantId, projectId, strategyId] }), client.invalidateQueries({ queryKey: ["strategies", tenantId, projectId] })]); }, onError: (error) => setMessage(error.message) });
  if (strategies.isPending || draft.isPending) return <div className="space-y-5"><Skeleton className="h-20" /><Skeleton className="h-96" /></div>;
  if (strategies.isError || !strategy || draft.isError || !draft.data) return <Card><CardContent className="flex min-h-60 flex-col items-center justify-center gap-3 pt-5"><p className="font-medium text-error-600">Strategy could not be loaded</p><Button onClick={() => void strategies.refetch()}>Retry</Button></CardContent></Card>;
  return <div className="min-w-0 space-y-6"><div><Link to=".." className="text-sm text-brand-500">← Strategies</Link><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold text-gray-900 dark:text-white">{strategy.name}</h1><p className="mt-1 text-sm text-gray-500">Draft revision {draft.data.revision}</p></div><Button variant="outline" onClick={() => void draft.refetch()}><RefreshCw />Reload</Button></div></div>
    <Card><CardContent className="space-y-4 pt-5"><SpecEditor value={source} onChange={(value) => { setSource(value); setMessage(""); }} format={format} onFormatChange={setFormat} /><div className="flex flex-wrap justify-end gap-2"><Button variant="outline" onClick={() => compile.mutate()} loading={compile.isPending}><CheckCircle2 />Validate</Button><Button variant="outline" onClick={() => save.mutate()} loading={save.isPending}><Save />Save draft</Button><Button onClick={() => publish.mutate()} loading={publish.isPending}><Rocket />Save & publish</Button></div>{message ? <p role="status" className="break-all rounded-xl bg-gray-50 p-3 text-sm text-gray-600 dark:bg-gray-800">{message}</p> : null}</CardContent></Card>
    {diagnostics.length ? <Card><CardHeader><CardTitle>Diagnostics</CardTitle></CardHeader><CardContent><ul className="space-y-3">{diagnostics.map((item, index) => <li key={`${item.code}-${index}`} className="rounded-xl border border-error-200 p-3 dark:border-error-500/30"><div className="flex flex-wrap gap-2 text-sm"><strong className="text-error-600">{item.code}</strong><code className="break-all text-gray-500">{item.path}</code></div><p className="mt-1 text-sm text-gray-600 dark:text-gray-300">{item.message}</p></li>)}</ul></CardContent></Card> : null}
    <Card><CardHeader><CardTitle>Published versions</CardTitle><span className="text-sm text-gray-500">{versions.data?.total ?? 0}</span></CardHeader><CardContent>{versions.isError ? <div className="flex items-center justify-between gap-3"><p className="text-sm text-error-600">Versions could not be loaded.</p><Button size="sm" onClick={() => void versions.refetch()}>Retry</Button></div> : versions.data?.items.length ? <ul className="space-y-3">{versions.data.items.map((version) => <li key={version.strategyVersionId} className="rounded-xl border border-gray-200 p-4 dark:border-gray-800"><p className="font-medium">Version {version.version}</p><p className="mt-1 break-all font-mono text-xs text-gray-500">{version.planHash}</p></li>)}</ul> : <p className="py-8 text-center text-sm text-gray-500">No published versions.</p>}</CardContent></Card>
  </div>;
}
